### ISSUE TITLE
Week one: match tracking

### ISSUE THREAD

**Issue by hudajkhan** [hudajkhan/KidsTasks#1]
3/16/20

- [x] 2 pages match skills (workbook)
- [x] 1 page addition/subtraction
- [x] 1 page multiplication/fractions

**Comment by hudajkhan** [comment]
This is more or less the pattern for the entire first week, with sections switched around a little based on how many pages are left or have been completed.
