### ISSUE TITLE
Week one: match tracking (N)

### ISSUE THREAD

**Issue by hudajkhan** [hudajkhan/KidsTasks#2]
3/16/20

- [x] 2 pages match skills (workbook)
- [x] 1 page addition/subtraction
- [x] 1 page multiplication/fractions

**Comment by hudajkhan** [comment]
pattern was similar for the week
